#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PAYLOAD=$(mktemp /tmp/resource-in.XXXXXX)
cat > "$PAYLOAD" <&0

DESTINATION=$1
echo "DESTINATION = $DESTINATION" 1>&2

TS=$(jq '.version.timestamp // empty' < "$PAYLOAD")
[ -z "$TS" ] && TS='"none"'

jq -n "{ version: { timestamp: \"$TS\" }, metadata: [] }" >&3

