#!/bin/bash

set -e

cd "${1}"

exec 3>&1
exec 1>&2
set +x

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > "${payload}" <&0

command="$(jq -r '.source.command' < "${payload}")"
args="$(jq -r '.params.args // ""' < "${payload}")"

(
    cd ${1}
    time $command $args
)

metadata="$(jq -n '{metadata: [] }')"
timestamp="$(jq -n "{version: { timestamp: "$(date +%s)" } }")"
echo "$timestamp $metadata " | jq -s add  >&3

